[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --prefer-offline"]

[phases.build]
cmds = [
  "cd server && PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1 npx prisma generate && cd ..",
  "pnpm run build"
]

[start]
cmd = "node server/src/index.js"

